### PR TITLE
all contributors bot!

### PR DESCRIPTION
**Pull request by ryansurf**
@K-dash https://github.com/ryansurf/cli-surf/issues/83

Setup for the all-contributors bot to work

Added instructions for how to use the bot in `CONTRIBUTING.md`

`.all-contributorsrc` is the config file, specified [here](https://allcontributors.org/docs/en/bot/installation)

## Summary by Sourcery

Integrate the all-contributors bot to manage and display project contributors. Update `README.md` to include the all-contributors badge and placeholder for the contributors list.

Documentation:
- Added instructions in `CONTRIBUTING.md` on how to use the all-contributors bot.

Chores:
- Configured the all-contributors bot by adding `.all-contributorsrc` file.

### CODE REVIEW

**Comment by K-dash** [comment]
LGTM🚀

As the next step,
I think we need to add all the contributors so far, can we call the bot on this PR?

**Review by K-dash — APPROVED** [review]

**Comment by K-dash** [comment]
https://allcontributors.org/docs/en/emoji-key

It seems we can also set the Contribution Types when calling the bot, how should we handle that?

**Comment by ryansurf** [comment]
> https://allcontributors.org/docs/en/emoji-key
> 
> I see that we can also set Contribution Types when we call the bot, should we add this setting as an operational rule?

I think the contribution setting is automatically applied, how do we make it optional? I might be a little silly right now but i don't see it

**Comment by K-dash** [comment]
@all-contributors please add @ryansurf  for code and doc

**Pull request merged**
