### PR TITLE
use std python image instead of alpine due to build issues

### PR DESCRIPTION
**Pull request by hotpocket**
the build is 1.9g  but to be fair 0.9 of that is dependencies that are installed. 

lots of research & time, little change.  how it should be :)

### CODE REVIEW

**Comment by ryansurf** [comment]
@hotpocket 

Sorry for the delay. Tested on my local, works great.

However, python slim works as well and is only 1.02 gb. Is there any particular reason you'd like to use the stock python image instead of this? We were using [slim](https://github.com/ryansurf/cli-surf/blob/2eecd0459abc6fd214d514dbd004eb584d2c3e44/Dockerfile) before alpine.

**Comment by ryansurf** [comment]
@all-contributors please add @hotpocket for infra

**Comment by hotpocket** [comment]
> @hotpocket
> 
> Sorry for the delay. Tested on my local, works great.
> 
> However, python slim works as well and is only 1.02 gb. Is there any particular reason you'd like to use the stock python image instead of this? We were using [slim](https://github.com/ryansurf/cli-surf/blob/2eecd0459abc6fd214d514dbd004eb584d2c3e44/Dockerfile) before alpine.
> 
> Edit: Apologies, just saw your [comment](https://github.com/ryansurf/cli-surf/issues/86#issuecomment-2276701297). I agree, we can make the slim conversion another ticket so we can get Docker working asap. Would you like to be assigned this one?
> 
> Merging this PR now

Sure, add me for the next ticket.  I've not done my homework yet on it, but from what I remember reading - docker-slim is a tool to modify an existing image to shrink it, not an image proper?   I'll find out as the ticket progresses.  Do we maybe want to host it at docker hub for a one stop shop pull & run ?

**Comment by ryansurf** [comment]
> > @hotpocket
> > Sorry for the delay. Tested on my local, works great.
> > However, python slim works as well and is only 1.02 gb. Is there any particular reason you'd like to use the stock python image instead of this? We were using [slim](https://github.com/ryansurf/cli-surf/blob/2eecd0459abc6fd214d514dbd004eb584d2c3e44/Dockerfile) before alpine.
> > Edit: Apologies, just saw your [comment](https://github.com/ryansurf/cli-surf/issues/86#issuecomment-2276701297). I agree, we can make the slim conversion another ticket so we can get Docker working asap. Would you like to be assigned this one?
> > Merging this PR now
> 
> Sure, add me for the next ticket. I've not done my homework yet on it, but from what I remember reading - docker-slim is a tool to modify an existing image to shrink it, not an image proper? I'll find out as the ticket progresses. Do we maybe want to host it at docker hub for a one stop shop pull & run ?

I wasn't referring to docker-slim (altough I suppose we can look into this aswell), but rather [python-slim](https://hub.docker.com/layers/library/python/slim/images/sha256-f3a12d3da806181f09987946869cb1171c6513f877f4db08ead679018cdd2b0f?context=explore), which doesn't shrink the image but instead skips the installation a good amount of packages that the stock python image ships with.

Docker hub seems like a good idea

**Pull request merged**
