### PR TITLE
Feature: Add Historical Weather Data Comparison

### PR DESCRIPTION
**Pull request by AITMAR-TAFE**
This pull request introduces a feature that enhances user experience by allowing users to compare current weather conditions with historical data from one year ago. This capability facilitates a better understanding of seasonal patterns, informs decision-making, and fosters awareness of climate trends. With versatile data presentation options through CLI prompts and a dedicated print function, users can access information in their preferred format. Comprehensive documentation and unit tests ensure clarity, maintainability, and reliability of the new functionality. Overall, this feature enriches user engagement and provides valuable insights into weather variability and its implications.
Related to issue nr #148 .

### Enhancements:

Implemented a two new function **get_uv_history** and **ocean_information_history** to fetch data one year ago.
Refactored **gather_data** function to include historical weather data.
Refactored **arguments_dictionary** , **set_output_values** and **print_ocean_data** for displaying past ocean data to maintain CLI prompt options.
Created a separate print function **print_historical_data** for displaying historical data as default.
Documented new functions and tests for clarity and maintainability.

### Testing:

Added unit tests for the new functionality to ensure accuracy. These tests also confirm the functionality works as intended and adheres to expected outcomes.

### Evidence of Implementation:

Screenshots: Included screenshot demonstrate how the feature looks in action.
open-source-evidence

## Summary by Sourcery

Add a feature to compare current weather conditions with historical data from one year ago, including UV index and ocean data. Implement new functions for fetching historical data and refactor existing functions to support this feature. Update documentation and add unit tests to ensure functionality and maintainability.

New Features:
- Introduce a feature to compare current weather conditions with historical data from one year ago, enhancing user experience and providing insights into seasonal patterns and climate trends.

Enhancements:
- Implement new functions get_uv_history and ocean_information_history to fetch historical weather data.
- Refactor gather_data function to include historical weather data.
- Update arguments_dictionary, set_output_values, and print_ocean_data to support displaying past ocean data.

Documentation:
- Document new functions and tests to ensure clarity and maintainability.

Tests:
- Add unit tests for the new historical data comparison functionality to ensure accuracy and reliability.

### CODE REVIEW

**Review by ryansurf — CHANGES_REQUESTED** [review]
Hey @AITMAR-TAFE, 

Nice work! I like that you've implemented testing, it looks thorough. 

Can you include some documentation on how to retrieve the past surf data in the readme? I'm trying to run this locally right now and it would be nice if there were some instructions on how to do this

**Comment by ryansurf** [comment]
@all-contributors please add @AITMAR-TAFE for code

**Comment by AITMAR-TAFE** [comment]
Hey @ryansurf,

Thank you for your feedback! I appreciate your kind words about the changes and the testing implementation.

I did consider removing the default print function but hesitated because it was specified in my original issue. However, I have now fixed the issue that caused the linter to fail and removed the print function as you suggested. I also updated the user arguments and revised the README file to include instructions on retrieving all historical data arguments. Lastly, I added some tests for historcial data arguments to ensure everything works smooth. 

Just let me know if there is anything else I can improve :) !

**Comment by ryansurf** [comment]
@AITMAR-TAFE just tested the changes, its working wonderfully!

Just an fyi, the [linter failed](https://github.com/ryansurf/cli-surf/actions/runs/11658721071/job/32692148653?pr=152) again. However, this time its asking for the formatter to be ran, so I'll just merge the PR and take care of it on my end. Thats on me, I should have advised you to run that as well (`make format`)

Regardless, great work! You've written clean, documented code with test cases. I really appreciate your efforts, thank you for the contribution

**Comment by AITMAR-TAFE** [comment]
Hey @ryansurf , thanks for the feedback, and apologies for the back and forth! I've now taken care of the formatter and added the suggested abbreviations for the arguments. I really appreciate you taking the time to review my work. Thanks again for the support!

**Review by ryansurf — APPROVED** [review]

**Pull request merged**
