### PR TITLE
new colors

### PR DESCRIPTION
**Pull request by mrmcgrain**
## Summary by Sourcery

Introduce new color codes for 'black' and 'cyan' to enhance the color options available in the application.

New Features:
- Add new color codes for 'black' and 'cyan' to the color dictionary in src/art.py.

### CODE REVIEW

**Comment by mrmcgrain** [comment]
Introduce new color codes for 'black' and 'cyan' to enhance the color options available in the application.

New Features:

Add new color codes for 'black' and 'cyan' to the color dictionary in src/art.py.

**Comment by ryansurf** [comment]
Hey @mrmcgrain, looks great! Can you add these new colors to [help.txt](https://github.com/ryansurf/cli-surf/blob/main/help.txt)? I'll merge your PR after that is done :+1:

**Comment by mrmcgrain** [comment]
Just updated the help.txt, Thank you for my first contribution experience..
While I did not do much, the process was very informative.

**Comment by ryansurf** [comment]
@mrmcgrain thank you for your contribution. So, another opportunity to learn just came up 😄 

The [linter failed](https://github.com/ryansurf/cli-surf/actions/runs/10218906115/job/28276136133?pr=78)! It looks like there's some trailing whitespace in the updated code. You can run `make lint` and `make format` to fix these (the formatter will automatically fix it for you). 

Let me know if that works

**Comment by mrmcgrain** [comment]
appears I do not have make on my windows machine...lol, looking into that
now

**Comment by ryansurf** [comment]
@mrmcgrain whoops, well you shouldn't need it. Checkout the  makefile and run the commands under lint & format

**Review by ryansurf — APPROVED** [review]

**Pull request merged**
